customhost = "emp.cfz3y9onpdfj.us-east-2.rds.amazonaws.com"
customuser = "rohit"
custompass = "rohit12sd"
customdb = "emp"
custombucket = "myaddemp"
customregion = "us-east-2"
customtable = "employee_image_table"
